// Mirrors internal/downloader.JobState. This isn't auto-generated by Wails
// (unlike ytdlp.Metadata/DownloadOptions) because it's only ever emitted as
// an event payload, not returned from a bound method.
export type JobStatus =
    | "queued"
    | "downloading"
    | "post_processing"
    | "completed"
    | "canceled"
    | "failed";

export interface JobProgress {
    JobID: string;
    Status: JobStatus;
    DownloadedBytes: number;
    TotalBytes: number;
    Percent: number;
    Speed: number;
    ETA: number;
    Message: string;
}

export interface DownloadItem extends JobProgress {
    url: string;
    title: string;
}
