// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckBinaries() {
  return window['go']['main']['App']['CheckBinaries']();
}

export function ChooseDownloadDir(arg1) {
  return window['go']['main']['App']['ChooseDownloadDir'](arg1);
}

export function ChooseFile(arg1) {
  return window['go']['main']['App']['ChooseFile'](arg1);
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function FetchPlaylist(arg1) {
  return window['go']['main']['App']['FetchPlaylist'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
