// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binmanager} from '../models';
import {ytdlp} from '../models';
import {config} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckBinaries():Promise<binmanager.BinaryStatus>;

export function ChooseDownloadDir(arg1:string):Promise<string>;

export function ChooseFile(arg1:string):Promise<string>;

export function FetchMetadata(arg1:string):Promise<ytdlp.Metadata>;

export function FetchPlaylist(arg1:string):Promise<ytdlp.Metadata>;

export function GetSettings():Promise<config.Settings>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartDownload(arg1:ytdlp.DownloadOptions):Promise<string>;
